---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 5m
  releaseName: clusters
  chart:
    spec:
      chart: ./multi-control/infrastructure/clusters-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
  values:
    clusters:
      cluster-01: 'a'