apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-cluster-02
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-02
  namespace: vcluster-cluster-02
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-02
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-02
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: cluster-02
  namespace: vcluster-cluster-02
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: ""
      repo: ""
      version: ""
    values: ""
  kubernetesVersion: 1.25.0
