---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/juozasg/flux-multi-demo.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusters-2
  namespace: flux-system
spec:
  interval: 5m
  releaseName: clusters-hr
  chart:
    spec:
      chart: ./multi-control/infrastructure/clusters-chart
      sourceRef:
        kind: GitRepository
        name: flux-system