---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-multi-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/annelaird/flux-multi-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-multi-demo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-multi-demo
